In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [2]:
tf.__version__

'2.7.0'

In [3]:
df = pd.read_csv("E:\Downloads\Churn_Modelling.csv")

In [8]:

pd.set_option('display.max_columns',14)
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [9]:
x = df.iloc[:,3:-1].values
y = df.iloc[:,-1].values

In [10]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [11]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:,2] = le.fit_transform(x[:,2])

In [13]:
x

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [14]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ohe = OneHotEncoder()
ct = ColumnTransformer(transformers= [('encoder', ohe, [1])], remainder = 'passthrough')
x =np.array(ct.fit_transform(x))

In [15]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [16]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state= 0)

In [17]:
from sklearn.preprocessing import StandardScaler 
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [18]:
ann = tf.keras.models.Sequential() 

In [50]:
ann.add(tf.keras.layers.Dense(units=5, activation= 'relu'))

In [51]:
ann.add(tf.keras.layers.Dense(units=5, activation= 'relu'))

In [52]:
ann.add(tf.keras.layers.Dense(units=1, activation= 'sigmoid'))

In [53]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [54]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 3s 4ms/step - loss: 0.5537 - accuracy: 0.7960
Epoch 2/100
250/250 [==============================] - 1s 4ms/step - loss: 0.5060 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 1s 4ms/step - loss: 0.5059 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 1s 4ms/step - loss: 0.5057 - accuracy: 0.7960
Epoch 5/100
250/250 [==============================] - 1s 4ms/step - loss: 0.5045 - accuracy: 0.7960
Epoch 6/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4978 - accuracy: 0.7960
Epoch 7/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4780 - accuracy: 0.7960
Epoch 8/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4463 - accuracy: 0.7960
Epoch 9/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4182 - accuracy: 0.7960
Epoch 10/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3926 - accura

250/250 [==============================] - 1s 4ms/step - loss: 0.3433 - accuracy: 0.8615
Epoch 82/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3434 - accuracy: 0.8618
Epoch 83/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3455 - accuracy: 0.8589
Epoch 84/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3432 - accuracy: 0.8589
Epoch 85/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3433 - accuracy: 0.8618
Epoch 86/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3431 - accuracy: 0.8605
Epoch 87/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3428 - accuracy: 0.8624
Epoch 88/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3447 - accuracy: 0.8612
Epoch 89/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3437 - accuracy: 0.8631
Epoch 90/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3427 - accuracy: 

In [55]:
ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))> 0.5 

array([[False]])

In [56]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [57]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1545   50]
 [ 217  188]]


0.8665